# Generated by Django 3.2 on 2023-07-21 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars_category_portal', '0004_rename_delear_carcategories_dealer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booking_number', models.IntegerField()),
                ('Customer_name', models.CharField(max_length=20)),
                ('Car_category', models.CharField(max_length=20)),
                ('Car_rental', models.DateTimeField(auto_now_add=True)),
                ('Car_mileage', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rent_return', models.DateTimeField(auto_now_add=True)),
                ('Days_return', models.CharField(max_length=3)),
                ('is_complete', models.BooleanField(default=False)),
                ('Car_dealer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars_category_portal.cardealer')),
                ('Cars_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars_category_portal.carcategories')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer_portal.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
