# Generated by Django 3.2 on 2023-07-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_category_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcategories',
            name='car_name',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
