# Generated by Django 3.2 on 2023-07-21 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_category_portal', '0002_carcategories_car_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carcategories',
            old_name='car_name',
            new_name='Car_name',
        ),
    ]
